Set custom AppCenter names
appKODE/build-publish-plugin pull request #14
Opened 2022-10-14 11:48 UTC by kabak89

ISSUE: https://github.com/appKODE/build-publish-plugin/issues/13

## 🚀 Description
In AppCenterDistributionConfig added appName property instead of appNamePrefix. Using appName developers can upload builds with different flavors and build types into single AppCenter application

2022-10-19 10:52 UTC, kode-android requested changes

2022-10-19 10:52 UTC, kode-android commented on example/app/build.gradle.kts
> +            appName.set("Android")
По идее тут надо добавить пример с register("debug") {
            appName.set("Android-debug")
}

и register("release")?

2022-10-19 10:52 UTC, kode-android commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/BuildPublishPlugin.kt
> +            it.appName.set(config.appName.orNull ?: "${outputConfig.baseFileName}-${buildVariant}")
Обращение через ornull может не сработать или поломать тот факт, что они lazy. Тут надо юзать flatMap, и обращение baseFileName и buildVariant скорее всего тоже просто так не сработает, первый лейзи, второй объект)

2022-10-19 10:52 UTC, kode-android commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/task/appcenter/AppCenterDistributionTask.kt
> +        description = "Application name in AppCenter. If appName isn't set plugin uses " +
Описание хорошее, но скорее всего оно должно быть на конфигах плагина, а не тут

2022-10-30 19:50 UTC, kabak89 commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/BuildPublishPlugin.kt
> +            it.appName.set(config.appName.orNull ?: "${outputConfig.baseFileName}-${buildVariant}")
не совсем понял про flatMap. предлагаешь маппить config.appName? насколько понял, если в config.appName нет значения, то и до flatMap не дойдет, так как там параметр nonnull

2022-10-30 19:56 UTC, kabak89 commented on example/app/build.gradle.kts
> +            appName.set("Android")
добавил

2022-10-30 19:58 UTC, kabak89 commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/task/appcenter/AppCenterDistributionTask.kt
> +        description = "Application name in AppCenter. If appName isn't set plugin uses " +
перенес в конфиги плагина

2022-10-31 21:56 UTC, kabak89 commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/BuildPublishPlugin.kt
> +            it.appName.set(config.appName.orNull ?: "${outputConfig.baseFileName}-${buildVariant}")
сделал так, что lazy не ломается

2022-11-30 09:27 UTC, kode-android approved these changes

2022-12-02 08:44 UTC, rinekri reviewed
Еще нужно поправить проблемы детекта

2022-12-02 08:44 UTC, rinekri commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/BuildPublishPlugin.kt
> +                        "$baseFileNameValue-${buildVariant.name}"
Думаю тут стоит сделать так, чтобы baseFileNameValue начинался с большой буквы, чтобы сохранить обратную совместимость еще лучше)) 

И еще меня тут немного волнует обращение к buildVariant.name, а не к tagBuildProvider, потому что эта штука доступна только в момент регистрации тасков, а не в момент использования их, мне кажется тут возможны проблемы, и лучше все-таки завязываться на тип сборки из тега. 

И тогда лучше чтобы он был главным 

tagBuildProvider.flatMap { tagBuildFile -> outputConfig.baseFileName.map { name -> 
name - fromJson(tagBuildFile.asFile).buildVariant
} }

2022-12-02 08:44 UTC, rinekri commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/BuildPublishPlugin.kt
> +                        "$baseFileNameValue-${buildVariant.name}"
Заодно надо бы проверить работоспособность этого, можешь создать AppCenter свой и попробовать задеплоить туда example сборки

2022-12-02 08:49 UTC, rinekri commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/BuildPublishPlugin.kt
> +                        "$baseFileNameValue-${buildVariant.name}"
Либо для простоты ты можешь просто запровайдить внутрь таска как проперти outputConfig.baseFileName, а там уже есть tagFile распаршенный, и там можно спокойно уже value этих значений объединить

2022-12-02 11:44 UTC, kabak89 commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/BuildPublishPlugin.kt
> +                        "$baseFileNameValue-${buildVariant.name}"
изменил, попробовал задеплоить, получилось

2022-12-03 13:59 UTC, rinekri commented
Проблемы детекта все еще актуальны, плюс лучше объединить в 1 коммит @kabak89

2022-12-09 10:49 UTC, kabak89 commented
поправил проблема детекта, объединил в 1 коммит

2022-12-09 11:26 UTC, rinekri approved these changes

2022-12-09 11:26 UTC, merged