DRAFT: [distribution] Enable upload apk to AppCenter
appKODE/build-publish-plugin pull request #2
Opened 2022-05-18 16:52 UTC by TrueWarg

Enable upload apk to AppCenter

2022-06-03 12:57 UTC, kode-android requested changes

2022-06-03 12:57 UTC, kode-android commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/BuildPublishPlugin.kt
> +            it.currentBuildVariant.set(buildVariant)
Думаю можео просто buildVariant, по факту у него другого и нету

2022-06-03 12:57 UTC, kode-android commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/task/AppCenterDistributionTask.kt
> +            project.logger.debug("failed to read changelog $e"); null
logger.error?

2022-06-03 14:23 UTC, TrueWarg commented on build.gradle.kts
> +    id("org.jetbrains.kotlin.android") version "1.6.20" apply false
Для семпла

2022-06-03 14:24 UTC, TrueWarg commented on example-dimensions/build.gradle.kts
> +        minSdk = 21
А в чем тут тяжесть? одна активти.

2022-06-03 14:25 UTC, TrueWarg commented on example-dimensions/build.gradle.kts
> +            "owner_name" to "android-team-kode.ru",
Не, это надо вообще убрать и заменить на <sample>

2022-06-03 14:26 UTC, TrueWarg commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/BuildPublishExtension.kt
> +    val appCenterConfig: MapProperty<String, String> =
Ну я тоже тогда про это говорил, мы как раз и договорились пока не рыпаться, а то долго)

2022-06-03 14:29 UTC, TrueWarg commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/task/AppCenterDistributionTask.kt
> +        val uploader = AppCenterUploader(ownerName, appName, project.logger, token)
Хм, то есть инстанс таска закэшируется? Я думал при каждом билде все будет заново создаваться.

2022-06-03 15:41 UTC, TrueWarg commented on gradle.properties
> +android.useAndroidX=true
Так не сработает

2022-06-06 11:13 UTC, TrueWarg commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/git/entity/Tag.kt
> +                ?: error("No buildVariants for ${tag.name}. Available variants: $buildVariants"),
Хехе, не 
![image](https://user-images.githubusercontent.com/32998850/172150320-4c23ae3b-9192-4dc6-8f96-a2f7497f248f.png)

2022-06-06 12:01 UTC, rinekri commented on plugin-build/plugin/src/main/java/ru/kode/android/build/publish/plugin/git/entity/Tag.kt
> +                ?: error("No buildVariants for ${tag.name}. Available variants: $buildVariants"),
😢

2022-06-06 12:57 UTC, merged